### ISSUE TITLE
Project can support thai font ?

### ISSUE THREAD

**Issue by Witawat** [easytarget/microPyEZfonts#25]
Hello

this project can support thai font ?

this simple :
```
สวัสดี ภาษาไทย น้ำมัน
```

this font.ttf
[THSarabunNew.zip](https://github.com/user-attachments/files/17541917/THSarabunNew.zip)

this list
```
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"#$%&'()*+,-./ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ ฯ ะ ั า ำ ิ ี ึ ื ุ ู ฺ ฻ ฼ ฽ ฾ ฿ เ แ โ ใ ไ ๅ ๆ ็ ่ ้ ๊ ๋ ์ ํ ๎ ๏ ๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙ ๚ ๛
```

**Comment by easytarget** [comment]
No, Sorry. Not that font.
- The font converter only supports fonts in `.bdf` format (as described in the docs).
- TrueType fonts such as the one in your zip file are not supported.

The micropython 'font-to-py' tool from Peter Hinch can convert truetype fonts into compatible python font packs; requirements and useage is a bit more complex than my tool, but it is compatible with a wider range of fonts including TrueType ones. See: https://github.com/peterhinch/micropython-font-to-py

There are many Thai characters in the Unifont and Efont packs that I provide, but I cannot help further

**Comment by Witawat** [comment]
> No, Sorry. Not that font.
> 
> * The font converter only supports fonts in  format (as described in the docs).`.bdf`
> * TrueType fonts such as the one in your zip file are not supported.
> 
> The micropython 'font-to-py' tool from Peter Hinch can convert truetype fonts into compatible python font packs; requirements and useage is a bit more complex than my tool, but it is compatible with a wider range of fonts including TrueType ones. See: https://github.com/peterhinch/micropython-font-to-py
> 
> There are many Thai characters in the Unifont and Efont packs that I provide, but I cannot help further


There are many Thai characters in the Unifont and Efont packs that I provide, but I cannot help further

have name ?
